spring:
  application:
    name: Gradle-Build-Tool
  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
  datasource:
    url: jdbc:postgresql://localhost:5432/Gradle
    username: RATANS
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: PathPatternParser

logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
    in:
      ratansgh:
        resilience: TRACE
  file:
    name: Gradle-Build-Tool/Logs/application.log
    max-size: 10MB
    max-history: 100
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
