auth_enabled: false # Disables authentication for Loki's API.

server:
  http_listen_port: 3100 # Loki listens for HTTP requests on port 3100.

#  defines global settings shared across Loki components
common:
  path_prefix: /loki # Base directory for Loki's data storage.
  replication_factor: 1 # Number of replicas for data (1 means no replication).
  ring:
    instance_addr: 127.0.0.1 # Address for this Loki instance in the ring.
    kvstore:
      store: inmemory # Use in-memory key-value store for ring data.

#  defines how Loki organizes, stores, and indexes log data over time
schema_config:
  configs:
    - from: 2022-01-11 # Start date for this schema configuration.
      store: boltdb-shipper # Use BoltDB Shipper for storage.
      object_store: filesystem # Store data on the filesystem.
      schema: v12 # Use schema version v12.
      index:
        prefix: index_ # Prefix for index files.
        period: 24h # Index files are created every 24 hours.

#  defines how and where Loki stores its log data and index files.storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index # Directory for active index files.
    cache_location: /tmp/loki/cache # Directory for index cache.
    cache_ttl: 24h # Cache time-to-live for index data.
  filesystem:
    directory: /tmp/loki/chunks # Directory for storing log chunks.
limits_config:
  allow_structured_metadata: false # Disables structured metadata in log entries.