server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot_logs
          __path__: /var/log/my-app/*.log
 